Repository foundation/foundation-sites, pull requests merged in 2018-06, with the labels that each got.

#11315 fix: lower breakpoint max value precision to avoid rounding #11313
  scss/components/_visibility.scss
  scss/util/_breakpoint.scss
  test/sass/_breakpoint.scss
Labels: Sass Mixins, bug fix, scss

#11316 fix: fix outdated Browserify transform configuration
  .browserslistrc
  docs/assets/img/gulpfile.js
  gulp/config.js
  gulp/tasks/check.js
  gulp/tasks/customizer.js
  gulp/tasks/sass.js
  package.json
Labels: bug fix, 📦build

#11334 chore: update dependencies (2018-06-13)
  package-lock.json
  package.json
  yarn.lock
Labels: dependencies, 💻 maintenance

#11333 chore: increase mocha tests timeout
  test/javascript/index.html
Labels: 💻 maintenance

#11341 fix: keep a scrollbar on document when Reveal opens #7831
  js/foundation.reveal.js
  scss/components/_reveal.scss
Labels: Reveal, bug fix

#11349 fix: revise Meteor "fourseven:scss" compatibility for Meteor<1.4.1 support
  package.js
Labels: bug fix, dependencies, meteor

#11350 fix: fix and update Bower config
  bower.json
Labels: bug fix

#11352 chore: resolve jQuery devDependency CVE
  package.json
  yarn.lock
Labels: dependencies, security, 💻 maintenance

#11356 fix: resolve invalid conflict resolution #11077 for v6.5
  js/foundation.magellan.js
Labels: Magellan, javascript, v6.5.0-rc.1

#11354 feat: automatically pick active menu item color by contrast
  scss/components/_menu.scss
  scss/settings/_settings.scss
Labels: menu, new feature, scss

#11361 fix: remove $-zf-size from non-responsive XY Grid classes generation
  scss/xy-grid/_classes.scss
Labels: bug fix, scss
