Repository foundation/foundation-sites, pull requests merged in 2019-01, with the labels that each got.

#11648 docs: fix various typos for "available"
  docs/pages/installation.md
  docs/pages/motion-ui.md
  docs/pages/xy-grid.md
Labels: 📖 documentation

#11650 chore: update dependencies (2019-01-13)
  .travis.yml
  package-lock.json
  package.json
  shrinkwrap.yaml
  yarn.lock
Labels: 💻 maintenance, 📦 dependencies

#11667 docs: OffCanvas correct transition time details
  js/foundation.offcanvas.js
Labels: Off-Canvas, 📖 documentation
