Repository foundation/foundation-sites, pull requests merged in 2020-02, with the labels that each got.

#11944 fix: trigger reflow / layout thrashing - closes #11943
  js/foundation.util.motion.js
Labels: javascript, javascript utilities

#11901 chore: update browserstack browser list
  browserstack.json
  test/javascript/components/accordionMenu.js
  test/javascript/components/offcanvas.js
Labels: 🚨tests

#11836 chore: remove jshint configuration
  .jshintrc
  bower.json
Labels: 🚚 build

#11835 fix: use the className field to prevent issues with function name man…
  js/foundation.core.plugin.js
Labels: javascript

#11831 refactor: use const and let
  customizer/lib/js.js
  customizer/lib/sass.js
  docs/assets/img/gulpfile.js
  js/foundation.core.utils.js
Labels: javascript

#11829 refactor: reformat code and mark unused parameters
  docs/assets/img/gulpfile.js
  js/foundation.core.js
  js/foundation.core.utils.js
  js/foundation.responsiveAccordionTabs.js
Labels: javascript

#11828 fix: correctly use the elementClassName
  js/foundation.tooltip.js
Labels: javascript

#11809 ci: add SonarCloud config file
  .sonarcloud.properties
Labels: 🚚 build

#11871 fix: resolve flebox button group bug
  docs/assets/scss/docs.scss
  docs/assets/scss/examples/_buttons.scss
  docs/pages/button-group.md
  scss/components/_button-group.scss
  test/visual/flex-grid/button-group.html
Labels: Button Group

#11908 Fix: Interchange initialises own triggers - closes #11403
  js/foundation.interchange.js
Labels: Interchange, javascript

#11698 feat(Abide): add validator-specific error messages
  docs/pages/abide.md
  js/foundation.abide.js
  test/visual/abide/error-messages.html
Labels: Abide

#11833 refactor: remove some unused code
  js/foundation.core.utils.js
  js/foundation.magellan.js
  js/foundation.slider.js
  js/foundation.sticky.js
  js/foundation.util.box.js
Labels: javascript

#11896 docs: remove Proxima Nova font
  docs/assets/fonts/ProximaNovaCond-Light.otf
  docs/assets/fonts/ProximaNovaCond-LightIt.otf
  docs/assets/fonts/ProximaNovaCond-Regular.otf
  docs/assets/fonts/ProximaNovaCond-RegularIt.otf
  docs/assets/fonts/ProximaNovaCond-Semibold.otf
  docs/assets/fonts/ProximaNovaCond-SemiboldIt.otf
  docs/assets/scss/_accordion-content.scss
  docs/assets/scss/_docs-footer.scss
  docs/assets/scss/docs.scss
Labels: 📖 documentation

#11872 fix: add Foundation Sites version number - closes #9510
  gulp/config.js
  scss/settings/_settings.scss
Labels: scss

#11832 fix: prevent error when the value of $anchorDims is null
  js/foundation.util.box.js
Labels: javascript

#11998 fix: partly revert #11457 - closes #11997
  js/foundation.dropdownMenu.js
Labels: Dropdown, Dropdown Menu, bug fix, javascript
