Repository foundation/foundation-sites, pull requests merged in 2020-03, with the labels that each got.

#12002 Update CDN URLs and SRI hashes
  docs/pages/installation.md
Labels: 📖 documentation

#11990 fix: use correct event name - closes #11989
  js/foundation.dropdownMenu.js
Labels: Dropdown Menu, javascript

#11994 Correct documentation for Submit buttons
  docs/pages/button.md
Labels: information needed, 📖 documentation

#12007 Chinese and Japanese are not RTL scripts.
  docs/pages/rtl.md
Labels: css, information needed

#11839 build: add GitHub Actions - closes #11823
  .github/workflows/main.yml
  README.md
  bower.json
  package.json
Labels: 🚚 build
